### ISSUE TITLE
Ложное срабатывание: предложения в скобках

### ISSUE THREAD

**Issue by Kakadu** [Darderion/map#32]
![image](https://user-images.githubusercontent.com/438226/168556838-4db88280-2752-481a-b228-7a2cc932b3a7.png)

Также он ругается на большую букву после скобки (не могу сделать норм скрин, потому что список гадостей и документ пролистываются одновременно)
![image](https://user-images.githubusercontent.com/438226/168557204-26bc4ecd-20f0-4a90-bf67-36ae4c1c61c1.png)

Согласно stackoverflow у меня должно быть все ОК https://rus.stackexchange.com/questions/36310

**Comment by chernishev** [comment]
Спасибо, посмотрим.

**Comment by Darderion** [comment]
Спасибо за репорт
