### ISSUE TITLE
404 при попытке перейти на страницу

### ISSUE THREAD

**Issue by pmokeev** [Darderion/map#36]
Находясь на странице с загруженной PDF, при открытии выпадающего меню
![image](https://user-images.githubusercontent.com/75482510/169376868-2c04f596-0a30-4540-92b2-654a1dbe5a4c.png)
и кликом средней кнопки мыши на любую из выпадающих кнопок сервис падает с 404
![image](https://user-images.githubusercontent.com/75482510/169376904-85dfff7b-cd49-4ef4-8e3d-120476e4ad65.png)

**Comment by Darderion** [comment]
Спасибо за репорт
